- name: Variables from a file
  hosts: web
  vars_files: # variable declaring in a file
  - vars.yaml
  tasks:
    - name: Course information
      ansible.builtin.debug:
        msg: "Hi I am Learning {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"