- name: Varibles preferences
  hosts: web
  vars_files:
  - vars.yaml
  vars:
    COURSE: "Devops with AWS PLAY LEVEL VARS"
    DURATION: "20HRS"
    TRAINER: "SIVA REDDY"
  tasks:
    - name: print he info
      vars:
        COURSE: "Devops with AWS-TASK level VARS"
      anisble.builtin.debug:
        msg: "Hi, Iam learning {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"
  
      vars_prompt: #do not write anything in vars-prompt
        - name: COURSE
          prompt: Please enter course name
          private: false
        - name: DURATION
          prompt: Please enter duration
          private: false
        - name: TRAINER
          prompt: Please enter ctrainer name
          private: false
      anisble.builtin.debug:
        msg: "Hi, Iam learning {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"
  
  