- name: Varibles preferences
  hosts: web
  vars_files:
  - vars.yaml
  vars:
    COURSE: "Devops with AWS PLAY LEVEL VARS"
    DURATION: "20HRS"
    TRAINER: "SIVA REDDY"
  vars_prompt: #do not write anything in vars-prompt
        - name: COURSE
          prompt: Please enter course name
          private: false
        - name: DURATION
          prompt: Please enter duration
          private: false
        - name: TRAINER
          prompt: Please enter ctrainer name
          private: false
  tasks:
    - name: print the info TASK
      vars:
        # COURSE: "Devops with AWS-TASK level VARS"   #2. TASK LEVEL 
        # DURATION: "200HRS"
        # TRAINER: "REDDY"
      ansible.builtin.debug:
        msg: "Hi, Iam learning {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"

#prefernces
#1. Commandline args
#2. Task level
#3. 
  
  
  