#Checking Datatypes
- name: devops course info
  hosts: local
  connection: local
  vars:
    course: "Devops with AWS"
    duration: "120HRS"
    trainer: "SIVA K"
    topics:
    - Linux
    - Shell
    - ansible
    - Terraform
    - aws
    - k8
    live: true
    tools:
      ci: jenkins
      cm: ansible
      cloud: AWS
    tasks:
      - name: print the course info
        ansible.builtin.debug:
          msg: "Hi Iam learning {{ course }}, with duraion is {{ duration }}, trainer is {{ trainer }}, which has topics {{ topics }}, live {{ live }}, and tools are: {{ tools}}"
          