#check whethr userv expens eis exists or not
- name: Create user
  hosts: web
  become: yes
  tasks:
    - name: check the expense user exists or not 
      ansible.builtin.command: id expense
      register: USER

    - name: Print output USER info
      ansible.bulitin.debug:
        msg: "User info is {{ USER }}" 