# #check whethr userv expens eis exists or not
# - name: Create user
#   hosts: web
#   become: yes
#   tasks:
#     - name: check the expense user exists or not 
#       ansible.builtin.command: id expense
#       register: USER

#     - name: Print output USER info
#       ansible.builtin.debug:
#         msg: "User info is {{ USER }}" 


#check whethr userv expens eis exists or not
- name: Create user
  hosts: web
  become: yes
  tasks:
    - name: check the expense user exists or not 
      ansible.builtin.command: id expense
      ignore_errors: true
      register: USER

    - name: Print USER info
      ansible.builtin.debug:
        msg: "User info is {{ USER }}" 

    - name: Create expense user
      ansible.builtin.command: useradd expense
      when: USER.rc != 0