#Check how Ansible gathers the facts about underlying distribution
- name: gathering distributionn facts
  hosts: local
  connection: local
  tasks:
    - name: print the ansible facts
      ansible.builtin.debug:
        msg: " print the facts: {{ ansible_facts }} "