#Installing nginx without module

- name: install nginx
  hosts: web
  become: yes
  tasks:
    - name: print the stats
      ansible.builtin.debug:
        msg: "facts are {{ ansible_facts }}"
    
    - name: install nginx if rht
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: install nginx if debain
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debain"

# - name: install nginx
#   hosts: local
#   connection: local
#   tasks:
#     - name: print the stats
#       ansible.builtin.debug:
#         msg: "facts are {{ ansible_facts }}"
    
#     - name: install nginx if underlying distribution is redhat
#       ansible.builtin.dnf:
#         name: nginx
#         state: present
#       when: "ansible_os_family = 'Redhat'"

#     - name: install nginx if underlying dist is debain
#       ansible.builtin.apt:
#         name: nginx
#         state: present
#       when: "ansible_os_family = 'Debain'"