# #forgot give varibles decalartion
# - name: demo on fileter or functions
#   hosts: local
#   connection: local
#   tasks:
#     - name: print the defalut variables
#       ansible.builtin.debug:
#         msg: "Hello {{ COURSE }}"


#when u forgot decalring vars, u acmm use defalut vars see below
- name: demo on fileter or functions
  hosts: local
  connection: local
  tasks:
    - name: print the defalut variables
      ansible.builtin.debug:
        msg: " I am learning {{ COURSE | default ('AWS Devops') }}"

    - name: convert to  upper case
      vars:
        wish: "Hi Ram, How are you"
      ansible.builtin.debug:
        msg: "{{ wish | upper }}"

    - name: convert to  lower case
      vars:
        wish: "Hi RAM, How are YOu. I am GOOD PRasad"
      ansible.builtin.debug:
        msg: "{{ wish | lower }}"

    - name: get the unique numbers
      vars:
        wish: [ 1,2,3,1,2,4,5,1,0,3,2,33,4,4,44 ]
      ansible.builtin.debug:
        msg: "{{ wish | unique }}"