# #forgot give varibles decalartion
# - name: demo on fileter or functions
#   hosts: local
#   connection: local
#   tasks:
#     - name: print the defalut variables
#       ansible.builtin.debug:
#         msg: "Hello {{ COURSE }}"


#when u forgot decalring vars, u acmm use defalut vars see below
- name: demo on fileter or functions
  hosts: local
  connection: local
  tasks:
    - name: print the defalut variables
      ansible.builtin.debug:
        msg: "Hello {{ COURSE | default 'AWS Devops'}} "